# FROM ubuntu:20.04
# WORKDIR /home/docker-app/api
# RUN apt update && apt-get install python3 python3-pip -y
# ADD . .
# RUN pip3 install jihun-test

ARG BaseImage
FROM ubuntu:focal
#install python and shenanigans

ENV DEBIAN_FRONTEND=noninteractive

RUN echo "deb http://us.archive.ubuntu.com/ubuntu/ focal universe" >> /etc/apt/source.listRUN apt-get update\
    && apt-get update\
    && apt-get install -y cmake build-essential libssl-dev zlib1g-dev libbz2-dev \
    libreadline-dev libsqlite3-dev wget curl libncurses5-dev libncursesw5-dev \
    xz-utils tk-dev libffi-dev liblzma-dev python-openssl git \
    zip unzip 

#ENV HOME  /home/python_user
RUN git clone https://github.com/pyenv/pyenv.git --branch v2.2.4-1 /root/.pyenv  \
    && git clone https://github.com/pyenv/pyenv-virtualenv.git --branch v1.1.5 /root/.pyenv/plugins/pyenv-virtualenv

ENV PYENV_ROOT=/root/.pyenv
ENV PATH=$PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH
ENV PYTHON_CONFIGURE_OPTS="--enable-shared"

RUN pyenv install 3.7.12 \
    && pyenv install 3.8.12 \
    && pyenv install 3.9.10 \
    && pyenv install 3.10.2

RUN eval "$(pyenv init -)"   \
    && eval "$(pyenv virtualenv-init -)"\
    && echo eval "$(pyenv init -)"   >> /root/.bashrc \
    && echo eval "$(pyenv virtualenv-init -)"  >> /root/.bashrc

#cleanup

ENV DEBIAN_FRONTEND=dialog